services:
  - docker

language: node_js

node_js:
  - "11"

jobs:
  include:
    - stage: test
      script: docker-compose run api npm test
    - stage: test
      script: docker-compose run web npm test

deploy:
  provider: script
  script: devops/bin/travis_deploy.sh
  on:
    branch: master
